name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Terraform version
        run: terraform version

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
      
